sudo : required 
serives:
    - docker



before_install:
    - docker build -t rkurd/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true rkurd/docker-react npm run test
    


deploy:
    - edge: true
    - provider: elasticbeanstalk
    - region: "us-east-2"
    - app: "docker"
    - env: "Docker-env "
    - bucket_name: "elasticbeanstalk-us-east-2-387178210594"
    - bucket_path: "docker"
    

    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY





